// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/dtako_events.proto

package dtako

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// イベント（dtako_rows.protoのEventと同じ定義を参照）
type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SrchId         string                 `protobuf:"bytes,1,opt,name=srch_id,json=srchId,proto3" json:"srch_id,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	UnkoNo         string                 `protobuf:"bytes,3,opt,name=unko_no,json=unkoNo,proto3" json:"unko_no,omitempty"`
	DriverId       string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartDatetime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_datetime,json=startDatetime,proto3" json:"start_datetime,omitempty"`
	EndDatetime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_datetime,json=endDatetime,proto3" json:"end_datetime,omitempty"`
	StartLatitude  float64                `protobuf:"fixed64,7,opt,name=start_latitude,json=startLatitude,proto3" json:"start_latitude,omitempty"`
	StartLongitude float64                `protobuf:"fixed64,8,opt,name=start_longitude,json=startLongitude,proto3" json:"start_longitude,omitempty"`
	StartCityName  string                 `protobuf:"bytes,9,opt,name=start_city_name,json=startCityName,proto3" json:"start_city_name,omitempty"`
	EndLatitude    float64                `protobuf:"fixed64,10,opt,name=end_latitude,json=endLatitude,proto3" json:"end_latitude,omitempty"`
	EndLongitude   float64                `protobuf:"fixed64,11,opt,name=end_longitude,json=endLongitude,proto3" json:"end_longitude,omitempty"`
	EndCityName    string                 `protobuf:"bytes,12,opt,name=end_city_name,json=endCityName,proto3" json:"end_city_name,omitempty"`
	Tokuisaki      string                 `protobuf:"bytes,13,opt,name=tokuisaki,proto3" json:"tokuisaki,omitempty"`
	Biko           string                 `protobuf:"bytes,14,opt,name=biko,proto3" json:"biko,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_dtako_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSrchId() string {
	if x != nil {
		return x.SrchId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetUnkoNo() string {
	if x != nil {
		return x.UnkoNo
	}
	return ""
}

func (x *Event) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Event) GetStartDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDatetime
	}
	return nil
}

func (x *Event) GetEndDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDatetime
	}
	return nil
}

func (x *Event) GetStartLatitude() float64 {
	if x != nil {
		return x.StartLatitude
	}
	return 0
}

func (x *Event) GetStartLongitude() float64 {
	if x != nil {
		return x.StartLongitude
	}
	return 0
}

func (x *Event) GetStartCityName() string {
	if x != nil {
		return x.StartCityName
	}
	return ""
}

func (x *Event) GetEndLatitude() float64 {
	if x != nil {
		return x.EndLatitude
	}
	return 0
}

func (x *Event) GetEndLongitude() float64 {
	if x != nil {
		return x.EndLongitude
	}
	return 0
}

func (x *Event) GetEndCityName() string {
	if x != nil {
		return x.EndCityName
	}
	return ""
}

func (x *Event) GetTokuisaki() string {
	if x != nil {
		return x.Tokuisaki
	}
	return ""
}

func (x *Event) GetBiko() string {
	if x != nil {
		return x.Biko
	}
	return ""
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrchId        string                 `protobuf:"bytes,1,opt,name=srch_id,json=srchId,proto3" json:"srch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventRequest) GetSrchId() string {
	if x != nil {
		return x.SrchId
	}
	return ""
}

// 運行NO指定でイベント一覧取得
type GetByUnkoNoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnkoNo        string                 `protobuf:"bytes,1,opt,name=unko_no,json=unkoNo,proto3" json:"unko_no,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // イベント種別フィルタ（空の場合は全て）
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // 開始時刻フィルタ（オプション）
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`          // 終了時刻フィルタ（オプション）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUnkoNoRequest) Reset() {
	*x = GetByUnkoNoRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUnkoNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUnkoNoRequest) ProtoMessage() {}

func (x *GetByUnkoNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUnkoNoRequest.ProtoReflect.Descriptor instead.
func (*GetByUnkoNoRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetByUnkoNoRequest) GetUnkoNo() string {
	if x != nil {
		return x.UnkoNo
	}
	return ""
}

func (x *GetByUnkoNoRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *GetByUnkoNoRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetByUnkoNoRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetByUnkoNoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUnkoNoResponse) Reset() {
	*x = GetByUnkoNoResponse{}
	mi := &file_proto_dtako_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUnkoNoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUnkoNoResponse) ProtoMessage() {}

func (x *GetByUnkoNoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUnkoNoResponse.ProtoReflect.Descriptor instead.
func (*GetByUnkoNoResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{3}
}

func (x *GetByUnkoNoResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// イベント種別ごとの集計
type AggregateByEventTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnkoNo        string                 `protobuf:"bytes,1,opt,name=unko_no,json=unkoNo,proto3" json:"unko_no,omitempty"`          // 運行NO（オプション、指定なしで全体集計）
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 開始時刻フィルタ（オプション）
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 終了時刻フィルタ（オプション）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateByEventTypeRequest) Reset() {
	*x = AggregateByEventTypeRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateByEventTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateByEventTypeRequest) ProtoMessage() {}

func (x *AggregateByEventTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateByEventTypeRequest.ProtoReflect.Descriptor instead.
func (*AggregateByEventTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{4}
}

func (x *AggregateByEventTypeRequest) GetUnkoNo() string {
	if x != nil {
		return x.UnkoNo
	}
	return ""
}

func (x *AggregateByEventTypeRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AggregateByEventTypeRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type AggregateByEventTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggregates    []*EventTypeAggregate  `protobuf:"bytes,1,rep,name=aggregates,proto3" json:"aggregates,omitempty"`
	Total         *EventTypeAggregate    `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"` // 全イベント種別の合計
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateByEventTypeResponse) Reset() {
	*x = AggregateByEventTypeResponse{}
	mi := &file_proto_dtako_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateByEventTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateByEventTypeResponse) ProtoMessage() {}

func (x *AggregateByEventTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateByEventTypeResponse.ProtoReflect.Descriptor instead.
func (*AggregateByEventTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{5}
}

func (x *AggregateByEventTypeResponse) GetAggregates() []*EventTypeAggregate {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

func (x *AggregateByEventTypeResponse) GetTotal() *EventTypeAggregate {
	if x != nil {
		return x.Total
	}
	return nil
}

type EventTypeAggregate struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // イベント種別
	Count     int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                         // イベント数
	// 時間集計
	TotalDurationMinutes float64 `protobuf:"fixed64,3,opt,name=total_duration_minutes,json=totalDurationMinutes,proto3" json:"total_duration_minutes,omitempty"` // 合計時間（分）
	AvgDurationMinutes   float64 `protobuf:"fixed64,4,opt,name=avg_duration_minutes,json=avgDurationMinutes,proto3" json:"avg_duration_minutes,omitempty"`       // 平均時間（分）
	// 距離集計（section_distance from db_service）
	TotalSectionDistance float64 `protobuf:"fixed64,5,opt,name=total_section_distance,json=totalSectionDistance,proto3" json:"total_section_distance,omitempty"` // 合計区間距離
	AvgSectionDistance   float64 `protobuf:"fixed64,6,opt,name=avg_section_distance,json=avgSectionDistance,proto3" json:"avg_section_distance,omitempty"`       // 平均区間距離
	// 走行距離集計（mileage差分 from db_service）
	TotalMileageDiff float64 `protobuf:"fixed64,7,opt,name=total_mileage_diff,json=totalMileageDiff,proto3" json:"total_mileage_diff,omitempty"` // 合計走行距離（終了メーター - 開始メーター）
	AvgMileageDiff   float64 `protobuf:"fixed64,8,opt,name=avg_mileage_diff,json=avgMileageDiff,proto3" json:"avg_mileage_diff,omitempty"`       // 平均走行距離
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventTypeAggregate) Reset() {
	*x = EventTypeAggregate{}
	mi := &file_proto_dtako_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeAggregate) ProtoMessage() {}

func (x *EventTypeAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeAggregate.ProtoReflect.Descriptor instead.
func (*EventTypeAggregate) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{6}
}

func (x *EventTypeAggregate) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventTypeAggregate) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EventTypeAggregate) GetTotalDurationMinutes() float64 {
	if x != nil {
		return x.TotalDurationMinutes
	}
	return 0
}

func (x *EventTypeAggregate) GetAvgDurationMinutes() float64 {
	if x != nil {
		return x.AvgDurationMinutes
	}
	return 0
}

func (x *EventTypeAggregate) GetTotalSectionDistance() float64 {
	if x != nil {
		return x.TotalSectionDistance
	}
	return 0
}

func (x *EventTypeAggregate) GetAvgSectionDistance() float64 {
	if x != nil {
		return x.AvgSectionDistance
	}
	return 0
}

func (x *EventTypeAggregate) GetTotalMileageDiff() float64 {
	if x != nil {
		return x.TotalMileageDiff
	}
	return 0
}

func (x *EventTypeAggregate) GetAvgMileageDiff() float64 {
	if x != nil {
		return x.AvgMileageDiff
	}
	return 0
}

var File_proto_dtako_events_proto protoreflect.FileDescriptor

const file_proto_dtako_events_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dtako_events.proto\x12\x05dtako\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x05\n" +
	"\x05Event\x12\x17\n" +
	"\asrch_id\x18\x01 \x01(\tR\x06srchId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x17\n" +
	"\aunko_no\x18\x03 \x01(\tR\x06unkoNo\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12A\n" +
	"\x0estart_datetime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rstartDatetime\x12=\n" +
	"\fend_datetime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vendDatetime\x12%\n" +
	"\x0estart_latitude\x18\a \x01(\x01R\rstartLatitude\x12'\n" +
	"\x0fstart_longitude\x18\b \x01(\x01R\x0estartLongitude\x12&\n" +
	"\x0fstart_city_name\x18\t \x01(\tR\rstartCityName\x12!\n" +
	"\fend_latitude\x18\n" +
	" \x01(\x01R\vendLatitude\x12#\n" +
	"\rend_longitude\x18\v \x01(\x01R\fendLongitude\x12\"\n" +
	"\rend_city_name\x18\f \x01(\tR\vendCityName\x12\x1c\n" +
	"\ttokuisaki\x18\r \x01(\tR\ttokuisaki\x12\x12\n" +
	"\x04biko\x18\x0e \x01(\tR\x04biko\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\x0fGetEventRequest\x12\x17\n" +
	"\asrch_id\x18\x01 \x01(\tR\x06srchId\"\xc0\x01\n" +
	"\x12GetByUnkoNoRequest\x12\x17\n" +
	"\aunko_no\x18\x01 \x01(\tR\x06unkoNo\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\";\n" +
	"\x13GetByUnkoNoResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.dtako.EventR\x06events\"\xa8\x01\n" +
	"\x1bAggregateByEventTypeRequest\x12\x17\n" +
	"\aunko_no\x18\x01 \x01(\tR\x06unkoNo\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x8a\x01\n" +
	"\x1cAggregateByEventTypeResponse\x129\n" +
	"\n" +
	"aggregates\x18\x01 \x03(\v2\x19.dtako.EventTypeAggregateR\n" +
	"aggregates\x12/\n" +
	"\x05total\x18\x02 \x01(\v2\x19.dtako.EventTypeAggregateR\x05total\"\xf1\x02\n" +
	"\x12EventTypeAggregate\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x124\n" +
	"\x16total_duration_minutes\x18\x03 \x01(\x01R\x14totalDurationMinutes\x120\n" +
	"\x14avg_duration_minutes\x18\x04 \x01(\x01R\x12avgDurationMinutes\x124\n" +
	"\x16total_section_distance\x18\x05 \x01(\x01R\x14totalSectionDistance\x120\n" +
	"\x14avg_section_distance\x18\x06 \x01(\x01R\x12avgSectionDistance\x12,\n" +
	"\x12total_mileage_diff\x18\a \x01(\x01R\x10totalMileageDiff\x12(\n" +
	"\x10avg_mileage_diff\x18\b \x01(\x01R\x0eavgMileageDiff2\xec\x01\n" +
	"\x11DtakoEventService\x120\n" +
	"\bGetEvent\x12\x16.dtako.GetEventRequest\x1a\f.dtako.Event\x12D\n" +
	"\vGetByUnkoNo\x12\x19.dtako.GetByUnkoNoRequest\x1a\x1a.dtako.GetByUnkoNoResponse\x12_\n" +
	"\x14AggregateByEventType\x12\".dtako.AggregateByEventTypeRequest\x1a#.dtako.AggregateByEventTypeResponseB3Z1github.com/yhonda-ohishi/dtako_events/proto;dtakob\x06proto3"

var (
	file_proto_dtako_events_proto_rawDescOnce sync.Once
	file_proto_dtako_events_proto_rawDescData []byte
)

func file_proto_dtako_events_proto_rawDescGZIP() []byte {
	file_proto_dtako_events_proto_rawDescOnce.Do(func() {
		file_proto_dtako_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dtako_events_proto_rawDesc), len(file_proto_dtako_events_proto_rawDesc)))
	})
	return file_proto_dtako_events_proto_rawDescData
}

var file_proto_dtako_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_dtako_events_proto_goTypes = []any{
	(*Event)(nil),                        // 0: dtako.Event
	(*GetEventRequest)(nil),              // 1: dtako.GetEventRequest
	(*GetByUnkoNoRequest)(nil),           // 2: dtako.GetByUnkoNoRequest
	(*GetByUnkoNoResponse)(nil),          // 3: dtako.GetByUnkoNoResponse
	(*AggregateByEventTypeRequest)(nil),  // 4: dtako.AggregateByEventTypeRequest
	(*AggregateByEventTypeResponse)(nil), // 5: dtako.AggregateByEventTypeResponse
	(*EventTypeAggregate)(nil),           // 6: dtako.EventTypeAggregate
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_proto_dtako_events_proto_depIdxs = []int32{
	7,  // 0: dtako.Event.start_datetime:type_name -> google.protobuf.Timestamp
	7,  // 1: dtako.Event.end_datetime:type_name -> google.protobuf.Timestamp
	7,  // 2: dtako.Event.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: dtako.Event.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 4: dtako.GetByUnkoNoRequest.start_time:type_name -> google.protobuf.Timestamp
	7,  // 5: dtako.GetByUnkoNoRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 6: dtako.GetByUnkoNoResponse.events:type_name -> dtako.Event
	7,  // 7: dtako.AggregateByEventTypeRequest.start_time:type_name -> google.protobuf.Timestamp
	7,  // 8: dtako.AggregateByEventTypeRequest.end_time:type_name -> google.protobuf.Timestamp
	6,  // 9: dtako.AggregateByEventTypeResponse.aggregates:type_name -> dtako.EventTypeAggregate
	6,  // 10: dtako.AggregateByEventTypeResponse.total:type_name -> dtako.EventTypeAggregate
	1,  // 11: dtako.DtakoEventService.GetEvent:input_type -> dtako.GetEventRequest
	2,  // 12: dtako.DtakoEventService.GetByUnkoNo:input_type -> dtako.GetByUnkoNoRequest
	4,  // 13: dtako.DtakoEventService.AggregateByEventType:input_type -> dtako.AggregateByEventTypeRequest
	0,  // 14: dtako.DtakoEventService.GetEvent:output_type -> dtako.Event
	3,  // 15: dtako.DtakoEventService.GetByUnkoNo:output_type -> dtako.GetByUnkoNoResponse
	5,  // 16: dtako.DtakoEventService.AggregateByEventType:output_type -> dtako.AggregateByEventTypeResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_dtako_events_proto_init() }
func file_proto_dtako_events_proto_init() {
	if File_proto_dtako_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dtako_events_proto_rawDesc), len(file_proto_dtako_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dtako_events_proto_goTypes,
		DependencyIndexes: file_proto_dtako_events_proto_depIdxs,
		MessageInfos:      file_proto_dtako_events_proto_msgTypes,
	}.Build()
	File_proto_dtako_events_proto = out.File
	file_proto_dtako_events_proto_goTypes = nil
	file_proto_dtako_events_proto_depIdxs = nil
}
