// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/dtako_events.proto

package dtako

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// イベント（dtako_rows.protoのEventと同じ定義を参照）
type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SrchId         string                 `protobuf:"bytes,1,opt,name=srch_id,json=srchId,proto3" json:"srch_id,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	UnkoNo         string                 `protobuf:"bytes,3,opt,name=unko_no,json=unkoNo,proto3" json:"unko_no,omitempty"`
	DriverId       string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartDatetime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_datetime,json=startDatetime,proto3" json:"start_datetime,omitempty"`
	EndDatetime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_datetime,json=endDatetime,proto3" json:"end_datetime,omitempty"`
	StartLatitude  float64                `protobuf:"fixed64,7,opt,name=start_latitude,json=startLatitude,proto3" json:"start_latitude,omitempty"`
	StartLongitude float64                `protobuf:"fixed64,8,opt,name=start_longitude,json=startLongitude,proto3" json:"start_longitude,omitempty"`
	StartCityName  string                 `protobuf:"bytes,9,opt,name=start_city_name,json=startCityName,proto3" json:"start_city_name,omitempty"`
	EndLatitude    float64                `protobuf:"fixed64,10,opt,name=end_latitude,json=endLatitude,proto3" json:"end_latitude,omitempty"`
	EndLongitude   float64                `protobuf:"fixed64,11,opt,name=end_longitude,json=endLongitude,proto3" json:"end_longitude,omitempty"`
	EndCityName    string                 `protobuf:"bytes,12,opt,name=end_city_name,json=endCityName,proto3" json:"end_city_name,omitempty"`
	Tokuisaki      string                 `protobuf:"bytes,13,opt,name=tokuisaki,proto3" json:"tokuisaki,omitempty"`
	Biko           string                 `protobuf:"bytes,14,opt,name=biko,proto3" json:"biko,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_dtako_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSrchId() string {
	if x != nil {
		return x.SrchId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetUnkoNo() string {
	if x != nil {
		return x.UnkoNo
	}
	return ""
}

func (x *Event) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Event) GetStartDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDatetime
	}
	return nil
}

func (x *Event) GetEndDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDatetime
	}
	return nil
}

func (x *Event) GetStartLatitude() float64 {
	if x != nil {
		return x.StartLatitude
	}
	return 0
}

func (x *Event) GetStartLongitude() float64 {
	if x != nil {
		return x.StartLongitude
	}
	return 0
}

func (x *Event) GetStartCityName() string {
	if x != nil {
		return x.StartCityName
	}
	return ""
}

func (x *Event) GetEndLatitude() float64 {
	if x != nil {
		return x.EndLatitude
	}
	return 0
}

func (x *Event) GetEndLongitude() float64 {
	if x != nil {
		return x.EndLongitude
	}
	return 0
}

func (x *Event) GetEndCityName() string {
	if x != nil {
		return x.EndCityName
	}
	return ""
}

func (x *Event) GetTokuisaki() string {
	if x != nil {
		return x.Tokuisaki
	}
	return ""
}

func (x *Event) GetBiko() string {
	if x != nil {
		return x.Biko
	}
	return ""
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrchId        string                 `protobuf:"bytes,1,opt,name=srch_id,json=srchId,proto3" json:"srch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetSrchId() string {
	if x != nil {
		return x.SrchId
	}
	return ""
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrchId        string                 `protobuf:"bytes,1,opt,name=srch_id,json=srchId,proto3" json:"srch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEventRequest) GetSrchId() string {
	if x != nil {
		return x.SrchId
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_proto_dtako_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{6}
}

func (x *ListEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_proto_dtako_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 空の位置情報を持つイベント検索
type FindEmptyLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"` // この日時以降
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEmptyLocationRequest) Reset() {
	*x = FindEmptyLocationRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEmptyLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEmptyLocationRequest) ProtoMessage() {}

func (x *FindEmptyLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEmptyLocationRequest.ProtoReflect.Descriptor instead.
func (*FindEmptyLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{8}
}

func (x *FindEmptyLocationRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// 日付範囲検索
type DateRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRangeRequest) Reset() {
	*x = DateRangeRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRangeRequest) ProtoMessage() {}

func (x *DateRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRangeRequest.ProtoReflect.Descriptor instead.
func (*DateRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{9}
}

func (x *DateRangeRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *DateRangeRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

// 運転手検索
type DriverSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverSearchRequest) Reset() {
	*x = DriverSearchRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverSearchRequest) ProtoMessage() {}

func (x *DriverSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverSearchRequest.ProtoReflect.Descriptor instead.
func (*DriverSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{10}
}

func (x *DriverSearchRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverSearchRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *DriverSearchRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

// 位置情報設定
type SetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrchId        string                 `protobuf:"bytes,1,opt,name=srch_id,json=srchId,proto3" json:"srch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocationRequest) Reset() {
	*x = SetLocationRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationRequest) ProtoMessage() {}

func (x *SetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationRequest.ProtoReflect.Descriptor instead.
func (*SetLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{11}
}

func (x *SetLocationRequest) GetSrchId() string {
	if x != nil {
		return x.SrchId
	}
	return ""
}

type SetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocationResponse) Reset() {
	*x = SetLocationResponse{}
	mi := &file_proto_dtako_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationResponse) ProtoMessage() {}

func (x *SetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationResponse.ProtoReflect.Descriptor instead.
func (*SetLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{12}
}

func (x *SetLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ジオコーディング
type SetGeoCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrchIds       []string               `protobuf:"bytes,1,rep,name=srch_ids,json=srchIds,proto3" json:"srch_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGeoCodeRequest) Reset() {
	*x = SetGeoCodeRequest{}
	mi := &file_proto_dtako_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGeoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGeoCodeRequest) ProtoMessage() {}

func (x *SetGeoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGeoCodeRequest.ProtoReflect.Descriptor instead.
func (*SetGeoCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{13}
}

func (x *SetGeoCodeRequest) GetSrchIds() []string {
	if x != nil {
		return x.SrchIds
	}
	return nil
}

type SetGeoCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGeoCodeResponse) Reset() {
	*x = SetGeoCodeResponse{}
	mi := &file_proto_dtako_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGeoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGeoCodeResponse) ProtoMessage() {}

func (x *SetGeoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGeoCodeResponse.ProtoReflect.Descriptor instead.
func (*SetGeoCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_events_proto_rawDescGZIP(), []int{14}
}

func (x *SetGeoCodeResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *SetGeoCodeResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_proto_dtako_events_proto protoreflect.FileDescriptor

const file_proto_dtako_events_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dtako_events.proto\x12\x05dtako\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x05\n" +
	"\x05Event\x12\x17\n" +
	"\asrch_id\x18\x01 \x01(\tR\x06srchId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x17\n" +
	"\aunko_no\x18\x03 \x01(\tR\x06unkoNo\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12A\n" +
	"\x0estart_datetime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rstartDatetime\x12=\n" +
	"\fend_datetime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vendDatetime\x12%\n" +
	"\x0estart_latitude\x18\a \x01(\x01R\rstartLatitude\x12'\n" +
	"\x0fstart_longitude\x18\b \x01(\x01R\x0estartLongitude\x12&\n" +
	"\x0fstart_city_name\x18\t \x01(\tR\rstartCityName\x12!\n" +
	"\fend_latitude\x18\n" +
	" \x01(\x01R\vendLatitude\x12#\n" +
	"\rend_longitude\x18\v \x01(\x01R\fendLongitude\x12\"\n" +
	"\rend_city_name\x18\f \x01(\tR\vendCityName\x12\x1c\n" +
	"\ttokuisaki\x18\r \x01(\tR\ttokuisaki\x12\x12\n" +
	"\x04biko\x18\x0e \x01(\tR\x04biko\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"8\n" +
	"\x12CreateEventRequest\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.dtako.EventR\x05event\"*\n" +
	"\x0fGetEventRequest\x12\x17\n" +
	"\asrch_id\x18\x01 \x01(\tR\x06srchId\"8\n" +
	"\x12UpdateEventRequest\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.dtako.EventR\x05event\"-\n" +
	"\x12DeleteEventRequest\x12\x17\n" +
	"\asrch_id\x18\x01 \x01(\tR\x06srchId\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x11ListEventsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"P\n" +
	"\x12ListEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.dtako.EventR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"L\n" +
	"\x18FindEmptyLocationRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\x80\x01\n" +
	"\x10DateRangeRequest\x127\n" +
	"\tdate_from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdateFrom\x123\n" +
	"\adate_to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06dateTo\"\xa0\x01\n" +
	"\x13DriverSearchRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x127\n" +
	"\tdate_from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateFrom\x123\n" +
	"\adate_to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06dateTo\"-\n" +
	"\x12SetLocationRequest\x12\x17\n" +
	"\asrch_id\x18\x01 \x01(\tR\x06srchId\"I\n" +
	"\x13SetLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x11SetGeoCodeRequest\x12\x19\n" +
	"\bsrch_ids\x18\x01 \x03(\tR\asrchIds\"Q\n" +
	"\x12SetGeoCodeResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2\xaf\x05\n" +
	"\x11DtakoEventService\x126\n" +
	"\vCreateEvent\x12\x19.dtako.CreateEventRequest\x1a\f.dtako.Event\x120\n" +
	"\bGetEvent\x12\x16.dtako.GetEventRequest\x1a\f.dtako.Event\x126\n" +
	"\vUpdateEvent\x12\x19.dtako.UpdateEventRequest\x1a\f.dtako.Event\x12D\n" +
	"\vDeleteEvent\x12\x19.dtako.DeleteEventRequest\x1a\x1a.dtako.DeleteEventResponse\x12A\n" +
	"\n" +
	"ListEvents\x12\x18.dtako.ListEventsRequest\x1a\x19.dtako.ListEventsResponse\x12O\n" +
	"\x11FindEmptyLocation\x12\x1f.dtako.FindEmptyLocationRequest\x1a\x19.dtako.ListEventsResponse\x12G\n" +
	"\x11SearchByDateRange\x12\x17.dtako.DateRangeRequest\x1a\x19.dtako.ListEventsResponse\x12G\n" +
	"\x0eSearchByDriver\x12\x1a.dtako.DriverSearchRequest\x1a\x19.dtako.ListEventsResponse\x12I\n" +
	"\x10SetLocationByGeo\x12\x19.dtako.SetLocationRequest\x1a\x1a.dtako.SetLocationResponse\x12A\n" +
	"\n" +
	"SetGeoCode\x12\x18.dtako.SetGeoCodeRequest\x1a\x19.dtako.SetGeoCodeResponseB3Z1github.com/yhonda-ohishi/dtako_events/proto;dtakob\x06proto3"

var (
	file_proto_dtako_events_proto_rawDescOnce sync.Once
	file_proto_dtako_events_proto_rawDescData []byte
)

func file_proto_dtako_events_proto_rawDescGZIP() []byte {
	file_proto_dtako_events_proto_rawDescOnce.Do(func() {
		file_proto_dtako_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dtako_events_proto_rawDesc), len(file_proto_dtako_events_proto_rawDesc)))
	})
	return file_proto_dtako_events_proto_rawDescData
}

var file_proto_dtako_events_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_dtako_events_proto_goTypes = []any{
	(*Event)(nil),                    // 0: dtako.Event
	(*CreateEventRequest)(nil),       // 1: dtako.CreateEventRequest
	(*GetEventRequest)(nil),          // 2: dtako.GetEventRequest
	(*UpdateEventRequest)(nil),       // 3: dtako.UpdateEventRequest
	(*DeleteEventRequest)(nil),       // 4: dtako.DeleteEventRequest
	(*DeleteEventResponse)(nil),      // 5: dtako.DeleteEventResponse
	(*ListEventsRequest)(nil),        // 6: dtako.ListEventsRequest
	(*ListEventsResponse)(nil),       // 7: dtako.ListEventsResponse
	(*FindEmptyLocationRequest)(nil), // 8: dtako.FindEmptyLocationRequest
	(*DateRangeRequest)(nil),         // 9: dtako.DateRangeRequest
	(*DriverSearchRequest)(nil),      // 10: dtako.DriverSearchRequest
	(*SetLocationRequest)(nil),       // 11: dtako.SetLocationRequest
	(*SetLocationResponse)(nil),      // 12: dtako.SetLocationResponse
	(*SetGeoCodeRequest)(nil),        // 13: dtako.SetGeoCodeRequest
	(*SetGeoCodeResponse)(nil),       // 14: dtako.SetGeoCodeResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_dtako_events_proto_depIdxs = []int32{
	15, // 0: dtako.Event.start_datetime:type_name -> google.protobuf.Timestamp
	15, // 1: dtako.Event.end_datetime:type_name -> google.protobuf.Timestamp
	15, // 2: dtako.Event.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: dtako.Event.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: dtako.CreateEventRequest.event:type_name -> dtako.Event
	0,  // 5: dtako.UpdateEventRequest.event:type_name -> dtako.Event
	0,  // 6: dtako.ListEventsResponse.events:type_name -> dtako.Event
	15, // 7: dtako.FindEmptyLocationRequest.since:type_name -> google.protobuf.Timestamp
	15, // 8: dtako.DateRangeRequest.date_from:type_name -> google.protobuf.Timestamp
	15, // 9: dtako.DateRangeRequest.date_to:type_name -> google.protobuf.Timestamp
	15, // 10: dtako.DriverSearchRequest.date_from:type_name -> google.protobuf.Timestamp
	15, // 11: dtako.DriverSearchRequest.date_to:type_name -> google.protobuf.Timestamp
	1,  // 12: dtako.DtakoEventService.CreateEvent:input_type -> dtako.CreateEventRequest
	2,  // 13: dtako.DtakoEventService.GetEvent:input_type -> dtako.GetEventRequest
	3,  // 14: dtako.DtakoEventService.UpdateEvent:input_type -> dtako.UpdateEventRequest
	4,  // 15: dtako.DtakoEventService.DeleteEvent:input_type -> dtako.DeleteEventRequest
	6,  // 16: dtako.DtakoEventService.ListEvents:input_type -> dtako.ListEventsRequest
	8,  // 17: dtako.DtakoEventService.FindEmptyLocation:input_type -> dtako.FindEmptyLocationRequest
	9,  // 18: dtako.DtakoEventService.SearchByDateRange:input_type -> dtako.DateRangeRequest
	10, // 19: dtako.DtakoEventService.SearchByDriver:input_type -> dtako.DriverSearchRequest
	11, // 20: dtako.DtakoEventService.SetLocationByGeo:input_type -> dtako.SetLocationRequest
	13, // 21: dtako.DtakoEventService.SetGeoCode:input_type -> dtako.SetGeoCodeRequest
	0,  // 22: dtako.DtakoEventService.CreateEvent:output_type -> dtako.Event
	0,  // 23: dtako.DtakoEventService.GetEvent:output_type -> dtako.Event
	0,  // 24: dtako.DtakoEventService.UpdateEvent:output_type -> dtako.Event
	5,  // 25: dtako.DtakoEventService.DeleteEvent:output_type -> dtako.DeleteEventResponse
	7,  // 26: dtako.DtakoEventService.ListEvents:output_type -> dtako.ListEventsResponse
	7,  // 27: dtako.DtakoEventService.FindEmptyLocation:output_type -> dtako.ListEventsResponse
	7,  // 28: dtako.DtakoEventService.SearchByDateRange:output_type -> dtako.ListEventsResponse
	7,  // 29: dtako.DtakoEventService.SearchByDriver:output_type -> dtako.ListEventsResponse
	12, // 30: dtako.DtakoEventService.SetLocationByGeo:output_type -> dtako.SetLocationResponse
	14, // 31: dtako.DtakoEventService.SetGeoCode:output_type -> dtako.SetGeoCodeResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_dtako_events_proto_init() }
func file_proto_dtako_events_proto_init() {
	if File_proto_dtako_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dtako_events_proto_rawDesc), len(file_proto_dtako_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dtako_events_proto_goTypes,
		DependencyIndexes: file_proto_dtako_events_proto_depIdxs,
		MessageInfos:      file_proto_dtako_events_proto_msgTypes,
	}.Build()
	File_proto_dtako_events_proto = out.File
	file_proto_dtako_events_proto_goTypes = nil
	file_proto_dtako_events_proto_depIdxs = nil
}
